# Week 6 — Midterm 1 Review

**COMP 1110 — Introduction to Computer Programming**

**Tuesday, October 13, 2026** · 9:30–11:20 AM · Room OM 1241

**Instructor:** Quan Nguyen

> **Midterm 1 is Thursday, October 15, 9:30–10:30, on Moodle.**
> Today is the only review session.

Say hello, take attendance (QR), and remind students there is **no new material today**.
Everything on these slides has already been taught in Weeks 1–5.

## Where we are

- **Last week (Week 5):** iteration — `while`, `for`, `range`, `break`/`continue`,
  and the counting / summing / max–min loop patterns.
- **This week (Week 6):** Tuesday is review and guided practice; **Thursday is Midterm 1**
  (Chapters 1–5, closed-book, on Moodle).
- **Next week (Week 7):** strings as sequences — indexing, slicing, string methods,
  and f-string output formatting.

## Today's outcomes

By the end of class you should be able to:

1. Trace a short program by hand and state its **exact** output. `[CLO 1]` `[CLO 4]`
2. Explain how `if`/`elif`/`else` chooses **exactly one** branch. `[CLO 1]`
3. Predict what a function call returns, and tell `return` apart from `print`. `[CLO 2]`
4. Hand-trace `while` and `for` loops, including `break` and `continue`. `[CLO 1]`
5. Find and fix a bug in code you did not write. `[CLO 4]`

## Reading to review

Everything on the midterm comes from these five chapters of
*Python for Everybody* (Trinket edition):

- [Ch. 1 — Introduction](https://books.trinket.io/pfe/01-intro.html)
- [Ch. 2 — Variables, expressions, statements](https://books.trinket.io/pfe/02-variables.html)
- [Ch. 3 — Conditional execution](https://books.trinket.io/pfe/03-conditional.html)
- [Ch. 4 — Functions](https://books.trinket.io/pfe/04-functions.html)
- [Ch. 5 — Iteration](https://books.trinket.io/pfe/05-iterations.html)

Re-do the chapter exercises **by hand on paper** before you re-run them.

## Midterm 1 — logistics

| | |
| :--- | :--- |
| **When** | Thursday, October 15 · quiz opens 9:30, closes 10:30 |
| **Length** | 60 minutes, one attempt |
| **Where** | Here, OM 1241, on **Moodle** |
| **Worth** | 25% of your final grade |
| **Covers** | Chapters 1–5 · CLO 1, 2, 4 |
| **Bring** | Your own laptop, **charged**, plus your TRU network login |

Question order is **randomized** — your neighbour's question 3 is not your question 3.

**Two question types, both practised today:**

1. **Trace-and-predict (auto-graded)** — given a short program, state its **exact**
   output, name the error, or say what it computes. "Exact" means spelling, spacing,
   capitalisation, and `3.0` vs `3` all matter.
2. **Short code-writing (hand-graded)** — type a function or small program into a Moodle
   text box. Marked for correctness **and readability**: meaningful names, 4-space
   indent, a comment where the logic is not obvious.

## Midterm 1 — the rules

**Closed-book means closed-book:**

- No textbook, no notes, no cheat sheet, no printouts.
- **No AI assistants** of any kind.
- No browsing beyond the Moodle quiz page.
- No communication with anyone, in the room or outside it.
- **You may not run Python.** No VS Code, no IDLE, no Colab, no online interpreter.

That last rule is why today is almost entirely *trace-by-hand* practice.

## If your laptop or Moodle fails mid-exam

**Raise your hand immediately.** Do not try to fix it silently — every minute you spend
troubleshooting on your own is a minute off your exam.

- I can **extend your individual attempt** or **reopen the quiz** while the exam is running.
- Moodle saves each answer as you go, so a crash rarely loses more than one question.
- Problems reported **after the quiz has closed cannot be verified and will not be remedied**.

Prevention: charge your laptop the night before, bring your charger, and log in to the
TRU network *before* 9:30.

## What NOT to worry about

Not on Midterm 1 — do not spend tonight on any of this:

- **Strings beyond `+` and `*`**: no indexing, slicing, or string methods (Ch. 6, Week 7).
- **Files**: no `open`, no reading or writing files (Ch. 7).
- **Lists, dictionaries, tuples, sets** (Ch. 8–10).
- **Classes and objects** (Ch. 14), and **`unittest`/docstrings** (Week 8).
- Anything from Chapters 11–13, 15–16 — those are not part of this course at all.
- Memorising the textbook's turtle/graphics examples, or PEP 8 rule numbers.

## How to trace code without running it

The method that earns marks on Thursday:

1. Draw a **variable table** on your scratch paper — one column per variable.
2. Walk the lines **in execution order**, not top to bottom: calls jump, loops repeat.
3. Update the table after **every** assignment. Cross out old values, don't erase.
4. Write each `print` output on a separate "output" line, immediately.
5. At the end, copy the output lines into Moodle **exactly** — including `.0` on floats.

We will use this on every question today.

## Chapter 1 refresher — what a program is

- A **program** is a sequence of instructions; the **interpreter** reads and executes
  Python one statement at a time.
- Building blocks: **input, output, sequential execution, conditional execution,
  repetition**.
- Three kinds of error:
  - **Syntax error** — Python cannot even read the line; nothing runs.
  - **Runtime error** (exception) — it starts, then crashes partway.
  - **Semantic/logic error** — it runs happily and gives the *wrong answer*.
- `#` starts a comment. Reserved words (`if`, `while`, `def`, …) cannot be variable names.

### Predict the output

```python
print("Grades")
print("=" * 7)
print("Ana", "Ben")
print("Ana" + "Ben")
```

What are the **four** lines of output?

In [1]:
print("Grades")
print("=" * 7)
print("Ana", "Ben")
print("Ana" + "Ben")

Grades
Ana Ben
AnaBen


**Why:** `print` with **several arguments** separates them with a single space
(`Ana Ben`); `+` on two strings **concatenates with nothing between** (`AnaBen`).
`"=" * 7` repeats the string 7 times. A common exam trap is writing `Ana Ben` for
both lines.

### Which kind of error?

Name the error type — **syntax**, **runtime**, or **semantic** — for each:

```python
# A
prnit("Hello")

# B
if x > 5
    print("big")

# C
celsius = 25
fahrenheit = celsius * 9 / 5 + 23   # meant 32
print(fahrenheit)
```

**A — runtime error.** The line is valid Python, so it parses fine; it fails when it
runs with `NameError: name 'prnit' is not defined`.

**B — syntax error.** The missing colon means Python cannot parse the file, so
**nothing at all runs** — not even a `print` on line 1.

**C — semantic error.** No error message, no crash. It prints `68.0` instead of `77.0`.
These are the dangerous ones: only tracing or testing finds them.

## Chapter 2 refresher — values, variables, expressions

- Types you need: `int`, `float`, `str`, `bool`. Check with `type(x)`.
- Operators: `+ - * / // % **`. Remember:
  - `/` **always** gives a `float` (`10 / 5` is `2.0`, not `2`).
  - `//` is floor division; `%` is the remainder; `**` is a power.
- Precedence: **P**arentheses, **E**xponent, **M**ultiply/**D**ivide, **A**dd/**S**ubtract,
  left to right — **except `**`, which groups right to left**.
- `input()` **always returns a string**. Convert with `int(...)` or `float(...)`.
- Names: `snake_case`, start with a letter or `_`, no reserved words.

### Predict the output

```python
total = 17
people = 5
print(total / people)
print(total // people)
print(total % people)
print(2 ** 3 ** 2)
print(10 - 2 * 3)
```

In [2]:
total = 17
people = 5
print(total / people)
print(total // people)
print(total % people)
print(2 ** 3 ** 2)
print(10 - 2 * 3)

3.4
3
2
512
4


**Why each line:**

- `17 / 5` → `3.4` — true division, always a float.
- `17 // 5` → `3` — floor division on two `int`s stays an `int`.
- `17 % 5` → `2` — the remainder (17 = 3×5 + 2).
- `2 ** 3 ** 2` → `2 ** 9` = `512`. `**` groups **right to left**; `(2**3)**2` would be 64.
- `10 - 2 * 3` → `4` — multiplication happens before subtraction.

### Find the bug

A student writes a sales-tax calculator. It crashes. Why, and what is the fix?

```python
price = input("Price: ")     # the user types 20
total = price * 1.05
print("You owe", total)
```

**The bug:** `input()` returns the **string** `"20"`, not the number `20`.
`"20" * 1.05` is meaningless, so Python raises

```
TypeError: can't multiply sequence by non-int of type 'float'
```

(`"20" * 3` would have worked — string repetition — which is why the error mentions
"sequence".)

**The fix:** convert before doing arithmetic.

In [3]:
price = "20"                 # imagine the user typed this
price = float(price)         # convert the string to a number
total = price * 1.05
print("You owe", total)

You owe 21.0


### Write the code

**Exam-style prompt.** Write a short program that:

1. starts from a variable `celsius` holding a temperature as a **string**,
2. converts it to a number,
3. computes Fahrenheit with `f = c * 9 / 5 + 32`,
4. prints a sentence containing the result.

You have 3 minutes. Write it on paper first — that is the exam condition.

In [4]:
celsius = "25"                    # imagine the user typed this
degrees_c = float(celsius)        # input is always a string
degrees_f = degrees_c * 9 / 5 + 32
print(degrees_c, "C is", degrees_f, "F")

25.0 C is 77.0 F


**Marking notes:** the conversion earns a mark, the formula earns a mark, the print
earns a mark. `snake_case` names and a comment on the non-obvious line earn the
readability mark. Writing `9 / 5` as `9 // 5` is a classic loss — it floors to `1`
and every answer comes out wrong by a wide margin.

## Chapter 3 refresher — conditional execution

- Comparison operators produce a **`bool`**: `==  !=  <  <=  >  >=`.
  `=` assigns; `==` compares. Mixing them up is a syntax error inside an `if`.
- Logical operators: `and` (both), `or` (either), `not` (flip).
- An `if`/`elif`/`else` chain runs **exactly one** branch — the **first** true one —
  then jumps past the rest.
- Two separate `if` statements are **not** a chain: both can run.
- `try` / `except` catches a runtime error so the program keeps going.

### Predict the output

```python
score = 95

if score >= 60:
    print("Pass")

if score >= 80:
    print("Good")
elif score >= 90:
    print("Excellent")
else:
    print("Keep trying")
```

In [5]:
score = 95

if score >= 60:
    print("Pass")

if score >= 80:
    print("Good")
elif score >= 90:
    print("Excellent")
else:
    print("Keep trying")

Pass
Good


**Why:** the first `if` is its own statement, so `Pass` prints. The second `if` starts a
new chain: `95 >= 80` is true, so `Good` prints and the chain **stops** — `elif` and
`else` are skipped even though `95 >= 90` is also true.

**The lesson:** in a chain, order your tests from the **most specific to the least
specific**. Put `>= 90` first, or `Excellent` can never print. This unreachable-branch
bug is a favourite midterm question.

### Find the bug

This is meant to print `teen` only for ages 13 through 19:

```python
age = 25
if age >= 13 or age <= 19:
    print("teen")
else:
    print("not a teen")
```

It prints `teen`. What is wrong?

**The bug:** `or` is true when **either** side is true. For `age = 25`,
`25 >= 13` is `True`, so the whole condition is `True` — and in fact *every* integer
satisfies one side or the other, so this condition is **always** `True`.

**The fix:** the age must satisfy **both** bounds, so use `and`.

In [6]:
age = 25
if age >= 13 and age <= 19:
    print("teen")
else:
    print("not a teen")

not a teen


### Predict the output

```python
value = "12a"

try:
    number = int(value)
    print("Converted:", number)
except ValueError:
    print("That is not a whole number")

print("Done")
```

In [7]:
value = "12a"

try:
    number = int(value)
    print("Converted:", number)
except ValueError:
    print("That is not a whole number")

print("Done")

That is not a whole number
Done


**Why:** `int("12a")` raises `ValueError`, so Python abandons the rest of the `try`
block immediately — `Converted:` is **never** printed — and jumps to `except`.
Because the error was handled, execution continues normally afterwards, so `Done`
still prints.

Trace trap: students often write `Converted: 12` first. Once a line in `try` raises,
**every remaining line in that block is skipped**.

## Chapter 4 refresher — functions

- `def name(parameters):` defines; `name(arguments)` calls. Defining runs **nothing**.
- **`return` sends a value back. `print` puts text on the screen.** They are not the same.
- A function with no `return` (or a bare `return`) hands back **`None`**.
- Parameters are **local**: assigning to one inside a function does not change the
  caller's variable.
- Once `return` executes, the function **stops immediately**.

### Predict the output

```python
def net_pay(hours, rate):
    pay = hours * rate
    return pay

def summary(name, amount):
    print(name, "earns", amount)

result = summary("Ana", net_pay(10, 12.5))
print(result)
```

In [8]:
def net_pay(hours, rate):
    pay = hours * rate
    return pay


def summary(name, amount):
    print(name, "earns", amount)


result = summary("Ana", net_pay(10, 12.5))
print(result)

Ana earns 125.0
None


**Why:** the inner call runs first — `net_pay(10, 12.5)` returns `125.0` (a float,
because `12.5` is a float). `summary` prints `Ana earns 125.0`. But `summary` has **no
`return`**, so it hands back `None`, which lands in `result` and prints as `None`.

**Exam point:** "prints something" and "returns something" are independent. A function
that only prints is useless in an expression — as the next question shows.

### Find the bug

```python
def biggest(a, b):
    if a > b:
        print(a)
    else:
        print(b)

x = biggest(3, 9)
print(x + 1)
```

It prints `9`, then crashes. What is the error, and what is the fix?

**The bug:** `biggest` **prints** its answer instead of **returning** it. So `x` is
`None`, and `None + 1` raises

```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

`TypeError ... 'NoneType'` almost always means *a function you called forgot to
`return`*.

**The fix:** return the value and let the caller decide whether to print it.

In [9]:
def biggest(a, b):
    if a > b:
        return a
    return b            # reached only when a <= b, since return exits at once


x = biggest(3, 9)
print(x + 1)

10


### Predict the output — scope

```python
count = 0

def bump(count):
    count = count + 1
    return count

print(bump(count))
print(count)
print(bump(bump(count)))
```

In [10]:
count = 0


def bump(count):
    count = count + 1
    return count


print(bump(count))
print(count)
print(bump(bump(count)))

1
0
2


**Why:** the `count` inside `bump` is a **local** parameter that merely starts as a copy
of the argument. Reassigning it changes only the local one, so the global `count` is
still `0` on line 2 of the output.

`bump(bump(count))` evaluates inside-out: `bump(0)` → `1`, then `bump(1)` → `2`.

**Trap:** if you answered `1 / 1 / 2`, you assumed the function mutated the global.
It cannot — assignment inside a function creates or updates a *local* name.

## Chapter 5 refresher — iteration

- `while <condition>:` repeats while the condition stays true. Something inside the loop
  must eventually make it false, or the loop never ends.
- `for i in range(...)`: `range(stop)` starts at 0; `range(start, stop)` **excludes**
  `stop`; `range(start, stop, step)` counts by `step`.
- `break` leaves the loop entirely. `continue` skips to the **next iteration**.
- Loop patterns: **counting** (`count = count + 1`), **summing** (`total = total + x`),
  **max/min** (keep a "best so far"). The accumulator is initialised **before** the loop.

### Predict the output

```python
total = 0
for i in range(1, 5):
    total = total + i
    print(i, total)
print("End", total)
```

How many lines? What is on each?

In [11]:
total = 0
for i in range(1, 5):
    total = total + i
    print(i, total)
print("End", total)

1 1
2 3
3 6
4 10
End 10


**Why:** `range(1, 5)` yields `1, 2, 3, 4` — **`5` is excluded**, so four iterations,
four lines, plus the final line = five lines.

Running total: 0+1=1, 1+2=3, 3+3=6, 6+4=10.

**Trap:** off-by-one. `range(1, 5)` has 4 values, not 5; `range(5)` has 5 values but
starts at `0`.

### Predict the output

```python
n = 0
while True:
    n = n + 1
    if n % 3 == 0:
        continue
    if n > 7:
        break
    print(n)
```

In [12]:
n = 0
while True:
    n = n + 1
    if n % 3 == 0:
        continue
    if n > 7:
        break
    print(n)

1
2
4
5
7


**Trace it:** `n` = 1 print · 2 print · 3 `continue` (multiple of 3) · 4 print ·
5 print · 6 `continue` · 7 print · 8 is not a multiple of 3 and `8 > 7`, so `break`.

Two lessons: `continue` jumps back to the top **without** reaching the later lines, and
a `while True` loop is only safe because some path reaches `break`. Note that `6` and
`3` never print even though the `break` test never sees them.

### Find the bug

Meant to print the sum 1 + 2 + 3 = 6, but prints `3`:

```python
for i in range(1, 4):
    total = 0
    total = total + i
print(total)
```

**The bug:** the accumulator `total` is reset to `0` **inside** the loop, so every
iteration throws away the previous sum. The last iteration computes `0 + 3`, which is
why `3` prints.

**The fix:** initialise the accumulator **once, before** the loop. Same rule for a
counter, and for a max/min "best so far".

In [13]:
total = 0                 # initialise once, before the loop
for i in range(1, 4):
    total = total + i
print(total)

6


## Live coding 1 — write it together

**Prompt (exam-style, hand-graded):** write a function `count_evens(start, stop)` that
returns how many even numbers there are from `start` up to **and including** `stop`.

`count_evens(1, 10)` should return `5`.

In [14]:
# Write count_evens(start, stop) here, together.
# Returns the number of even values from start through stop, inclusive.

In [15]:
def count_evens(start, stop):
    count = 0                       # counter pattern: initialise before the loop
    for number in range(start, stop + 1):   # +1 makes stop inclusive
        if number % 2 == 0:
            count = count + 1
    return count


print(count_evens(1, 10))
print(count_evens(2, 2))
print(count_evens(5, 4))

5
1
0


### Live coding 2 — stretch prompt

Write `grade_letter(score)` returning `"A"` for 90+, `"B"` for 80–89, `"C"` for 70–79,
and `"F"` otherwise — then drive it with a `while` loop instead of four separate calls.

In [16]:
# Write grade_letter(score) here, together, then drive it with a loop.

In [17]:
def grade_letter(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    return "F"


score = 100
while score >= 40:
    print(score, grade_letter(score))
    score = score - 20        # 100, 80, 60, 40 then stops

100 A
80 B
60 F
40 F


## Errors you will meet on Thursday (1 of 2)

**`SyntaxError: invalid syntax` / `expected ':'`**
A missing colon after `if`, `while`, `for`, or `def`, or `=` where `==` belongs.
Nothing runs at all — check the line *above* the one Python names.

**`IndentationError: expected an indented block`**
The line after a colon must be indented by 4 spaces. Mixing tabs and spaces gives
`TabError`.

In [18]:
number = 5
if number = 5:
    print("five")

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1948007141.py, line 2)

**Read it as:** `=` assigns, and you cannot assign inside a condition. Python even
suggests `==`. On a trace question, the correct answer is *"nothing is printed — it is
a syntax error"*, not the output the code looks like it wants.

## Errors you will meet on Thursday (2 of 2)

**`TypeError: can't multiply sequence by non-int...`** — arithmetic on a string that
came from `input()`. Convert with `int()` / `float()`.

**`TypeError: ... 'NoneType' and 'int'`** — you used the result of a function that
forgot to `return`.

**`ValueError: invalid literal for int() with base 10`** — `int("12a")`. Wrap it in
`try`/`except ValueError` if bad input is expected.

**`NameError: name 'x' is not defined`** — a typo, or a variable used before it is
assigned, or a **local** variable used outside its function.

In [19]:
total = int("12a")
print(total)

ValueError: invalid literal for int() with base 10: '12a'

**Read the last line first:** the error type is `ValueError` and the message names the
offending text, `'12a'`. Note it is *not* a `SyntaxError` — the line is perfectly legal
Python that fails only when it runs, which is exactly the syntax-vs-runtime distinction
from Chapter 1.

## Summary — the six things that decide your mark

1. **`/` gives a float, `//` floors, `%` is the remainder** — and `input()` is a string.
2. **An `if`/`elif`/`else` chain runs exactly one branch**; two separate `if`s can both run.
3. **`return` ≠ `print`.** No `return` means the call evaluates to `None`.
4. **Parameters are local.** Assigning to one never changes the caller's variable.
5. **`range(a, b)` excludes `b`**; initialise accumulators *before* the loop.
6. **Trace on paper with a variable table.** You cannot run Python on Thursday.

## Worksheets and what to do tonight

- **No worksheet is released this week** — Thursday is the midterm. Worksheet 5 was
  released Oct 8 and is due **Tuesday, October 20** (the extra week is because of the
  midterm). Worksheet 6 (strings, Chapter 6) is released **Thursday, October 22**.
- Tonight, in this order:
  1. Take the **practice quiz on Moodle** — same interface, same timer.
  2. Re-trace Worksheets 1–4, especially every trace-and-explain question you lost marks on.
  3. Re-read the Chapter 3 and 5 summaries.
- Then sleep. Tracing code is a rested-brain activity.

## Next class — Thursday, October 15

**MIDTERM 1.** Room OM 1241, quiz opens **9:30**, closes **10:30**.

- Arrive by 9:20 with a **charged laptop** and your TRU login working.
- Nothing on your screen but the Moodle quiz page.
- Something breaks? **Raise your hand right away.**

Week 7 (Oct 20) picks up with **strings**: indexing, slicing, methods, and f-strings.
Good luck — you have done the practice.